# Generated by Django 4.1.4 on 2022-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_types',
            field=models.CharField(choices=[('essential', '🔥 essential'), ('later', '🐢 later')], default='essential', max_length=20),
        ),
    ]
