# Generated by Django 4.1.4 on 2022-12-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_todo_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_types',
            new_name='type',
        ),
    ]
