# Generated by Django 4.1.4 on 2022-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_todo_types_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('🔥 essential', '🔥 essential'), ('🐢 later', '🐢 later')], default='essential', max_length=20),
        ),
    ]
