# Generated by Django 4.1.4 on 2022-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('essential', 'essential'), ('later', 'later')], default='essential', max_length=20),
        ),
    ]
